apiVersion: v1
data:
  identity: {{ FLUX_SSH_DEPLOY_PRIVATE_KEY | b64encode }}
  identity.pub: {{ FLUX_SSH_DEPLOY_PUBLIC_KEY | b64encode }}
kind: Secret
metadata:
  name: flux-git-deploy
  namespace: flux
type: Opaque