---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached
  template:
    metadata:
      labels:
        name: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.6.8
        imagePullPolicy: IfNotPresent
        args:
        - -m 64
        - -p 11211
        ports:
        - name: clients
          containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: flux
spec:
  clusterIP: None
  ports:
    - name: memcached
      port: 11211
  selector:
    name: memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io.port: '3031'
      labels:
        name: flux
    spec:
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
      - name: flux
        image: fluxcd/flux:{{ FLUX_GIT_IMAGE_VERSION }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: git-keygen
          mountPath: /var/fluxd/keygen
        args:
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --git-email={{ FLUX_GIT_EMAIL }}
        - --git-url={{ FLUX_GIT_URL }}
        - --git-branch={{ FLUX_GIT_BRANCH }}
        - --listen-metrics=:3031
        - --sync-interval=1m
        - --git-path={{ FLUX_GIT_PATH }}
        - --git-ci-skip=true
        - --git-ci-skip-message=[CI SKIP]